name: medcare
description: "Projet d'application mobile pour les personnes atteints de maladies chroniques en France"

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Package for interactive calendar
  table_calendar: ^3.0.9
  
  # Package for date formatting
  intl: ^0.18.1
  supabase_flutter: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true